title: MOLGENIS
email: support@molgenis.org
description: "MOLGENIS is an open-source platform for FAIR scientific data management in genomics, biobanking, and rare disease research."
layout: blue #default layout
url: https://www.molgenis.org

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  partners:
    output: true
  tools:
    output: true
  communities:
    output: true