imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

adminPassword: admin
image:
  repository: nginx
  tag: alpine
  pullPolicy: Always

ingress:
  enabled: true
  hosts:
  - host: www.molgenis.org
  path: /

service:
  type: ClusterIP
  port: 80