version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  slack: circleci/slack@4.4.4

jobs:
  build:
    docker:
    - image: molgenis/molgenis-org-ci:v1.0.1
    steps:
    - checkout
    - run:
        name: Jekyll build
        command: |
          bundle exec jekyll doctor
          bundle exec jekyll build
    - run:
        name: prepare azure
        command: |
          az login --service-principal --tenant ${AZURE_SP_TENANT} -u ${AZURE_CLIENT_ID} -p ${AZURE_SECRET}
          az aks get-credentials -g ${RESOURCE_GROUP} -n ${RESOURCE_GROUP}
          kubectl config set-cluster ${RESOURCE_GROUP}
          kubectl config use-context ${RESOURCE_GROUP}
    - run:
        name: update preview
        command: |
          NAME="preview-molgenis-org-pr-${CIRCLE_PULL_REQUEST##*/}"
          echo "${NAME}"
          helm repo add onechart https://chart.onechart.dev
          helm template my-release onechart/onechart \
            --set image.repository=nginx \
            --set image.tag=1.19.3 \
            --set ingress.host=${NAME}.dev.molgenis.org/
          kubectl delete namespace $NAME || true
          kubectl create namespace ${NAME}
          echo ${CERTDEVMOLGENIS_KEY} | base64 --decode >> /tmp/cert_key
          echo ${CERTDEVMOLGENIS_PEM} | base64 --decode >> /tmp/cert_pem
          kubectl create secret tls "dev.molgenis.org" --key /tmp/cert_key --cert /tmp/cert_pem -n ${NAME}
          helm upgrade --install ${NAME} ./helm-chart --namespace ${NAME}
workflows:
  version: 2
  build:
    jobs:
    - build
