apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    app: {{ template "website.name" . }}
    chart: {{ template "website.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "website.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "website.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: data-loader
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "kubectl cp /mnt/html-files/. {{ .PodName }}:/usr/share/nginx/html"]
        volumeMounts:
        - name: html-volume
          mountPath: /mnt/html-files
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: {{ include "website.fullname" . }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html

restartPolicy: Always
status: {}
