apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    app: {{ template "website.name" . }}
    chart: {{ template "website.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "website.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "website.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: website-html-volume
        configMap:
          name: website-files-configmap
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
      volumeMounts:
        - name: website-html-volume
          mountPath: /usr/share/nginx/html
      command: ["/bin/sh", "-c", "tar -xzvf /usr/share/nginx/html/website.tar.gz -C /usr/share/nginx/html/ && nginx -g 'daemon off;'"]

restartPolicy: Always
status: {}
