apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "molgenis-org.fullname" . }}
  labels:
    app: {{ include "molgenis-org.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "molgenis-org.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "molgenis-org.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: nginx:alpine
        ports:
        - containerPort: 80
      volumeMounts:
      - name: static-files
        mountPath: /usr/share/nginx/html