{{- if .Values.ingress.enabled }}
  {{- $fullName := include "molgenis-org.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "molgenis-org.fullname" . }}
  labels:
    app: {{ template "molgenis-org.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    {{- range .Values.ingress.hosts }}
  - hosts:
    - {{ .host | quote }}
    secretName: dev.molgenis.org
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service  # Replace with the name of your service
            port:
              number: 80
  {{- end }}
{{- end }}
