apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "website.fullname" . }}-postgres-pv
  labels:
    app: {{ template "website.name" . }}
    chart: {{ template "website.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
status: {}
