apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ include "website.fullname" . }}
    labels:
      app: {{ template "website.name" . }}
      chart: {{ template "website.chart" . }}
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
  spec:
    type: {{ .Values.service.type }}
    ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
    selector:
      {{- include "website.selectorLabels" . | nindent 8}}
  status:
    loadBalancer: {}
